Automated script to install this WONDERFUL tool!
xulongwu4/solus-nvidia-optimus-manager pull request #6
Opened 2019-10-07 00:05 UTC by kz6fittycent

First, THANK YOU for creating this awesome tool to enable switchable graphics in Solus. I LOVE it!

I've created a script that will automate the installation for users and it supports the main 3 DE's (MATE, Budgie and Gnome). 

I've tested it several times and run it on my own machine(s). 

I don't know if you're still supporting this repo but I'd like to submit my PR anyway. Otherwise, I'm happy to keep things going as I can.

2020-01-11 14:57 UTC, bertaga commented
Why do you put `99-nvidia.conf` in `${GDM}` for Budgie desktop (it uses LightDM)?
You can create a function for things you repeat (`#SYSTEM PREP`).
There is no `else` statement which is bad because you need to say it if your script does not recognize the DE.
There is no check for su privilege.
You should create your variables using `readonly`.
Why so much sleep?

2020-01-11 15:12 UTC, ghost requested changes
I already posted a comment but I discovered this feature ^^

2020-01-11 15:12 UTC, bertaga commented on nvidia-optimus-installer.sh
> +    sudo eopkg it pciutils
This part is repeated three times

2020-01-11 15:12 UTC, bertaga commented on nvidia-optimus-installer.sh
> +fi
No else statement

2020-01-11 15:12 UTC, bertaga commented on nvidia-optimus-installer.sh
> +    sudo eopkg it pciutils
1/3

2020-01-11 15:12 UTC, bertaga commented on nvidia-optimus-installer.sh
> +    sudo eopkg it pciutils
2/3

2020-01-11 15:12 UTC, bertaga commented on nvidia-optimus-installer.sh
> +    sudo eopkg it pciutils
3/3

2020-01-11 15:12 UTC, bertaga commented on nvidia-optimus-installer.sh
> +SYSD=nvidia-optimus-autoconfig.service
Should be readonly

2020-01-19 03:18 UTC, kz6fittycent commented
> Why do you put `99-nvidia.conf` in `${GDM}` for Budgie desktop (it uses LightDM)?
> You can create a function for things you repeat (`#SYSTEM PREP`).
> There is no `else` statement which is bad because you need to say it if your script does not recognize the DE.
> There is no check for su privilege.
> You should create your variables using `readonly`.
> Why so much sleep?

I think you should double-check the defaults for Budgie again using the commands listed in the original README. Several users have confirmed these settings for Budgie across several machines. 

As far as "repeating" things, it really doesn't matter, does it? 

Read only isn't necessary. There's no real security issue here. It's a ONE time script that plops files in place for the user. 

Why don't you redo the script the way you like it? I did a PR out of courtesy.

2020-01-19 03:18 UTC, closed without merging

2021-04-29 18:33 UTC, VoltaVX commented
@kz6fittycent I don't think Franck said those things out of bad faith or to be an ass, but wanted to keep some level of code-cleanness on his project. I'm sure he appreciates your contribution and everything, I mean, he did go out of his way to give you some advice on stuff ya can fix/clean